### PR TITLE
Expose `remote_ip` and `remote_port` for each WireGuard peer

### PR DESCRIPTION
**Pull request by Ma27**
Now each peer also provides the fields `remote_ip` and `remote_port` if available in the output for Prometheus.

### CODE REVIEW

**Comment by Ma27** [comment]
Btw I guess that this should be an optional feature that can be enabled by a flag, right? When I think a little bit about this, I don't think that we want this for all cases.

**Comment by MindFlavor** [comment]
Nice! Thanks!

**Comment by Ma27** [comment]
@MindFlavor Umm... as meantioned yesterday, shouldn't we make this feature optional? Because there's one "breaking change" that might not be liked by every user: when you have a mobile client that regularly switches networks, you'll have multiple results in your grafana because of different remote IPs.

**Comment by MindFlavor** [comment]
Makes sense... I will try to add a startup flag before pushing the new version.

**Comment by Ma27** [comment]
Great, thanks! :)

**Pull request merged**
